version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "DEPS UPDATE: "
    labels:
      - dependencies
    groups:
      core:
        patterns:
          - "^axios"
          - "^discord.js"
          - "^dotenv"
          - "^file-type"
          - "^node-pty"
          - "^shell-escape"
          - "^strip-ansi"
          - "^winston"
      dev-deps:
        patterns:
          - "^eslint"
          - "^prettier"
          - "^@eslint"
          - "^eslint-config-prettier"
          - "^eslint-plugin-.*"
          - "^typescript-eslint"
          - "^typescript"
          - "^ts-node"
          - "^@types/"
          - "^husky"
          - "^jiti"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ACTIONS UPDATE: "
    labels:
      - actions