services:
  discos:
    container_name: DiscOS
    image: discos:latest
    hostname: discos-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Users in db.json does not exist in the container, use root for testing
      - PTY_TEST_MODE=1
    volumes:
      - ./db.json:/discos/db.json
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"